### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by cheezychicken** [bermudalocket/Euclid#1]
Dunno if this is overly useful, but got a nullpointer crash:
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 30/07/19 20:41
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.bermudalocket.euclid.wecui.GhostWireframeHelper.expand(GhostWireframeHelper.java:16)
	at net.minecraft.class_408.lambda$onRender$3(class_408.java:567)
	at net.minecraft.class_408$$Lambda$2356/1362089915.run(Unknown Source)
	at com.bermudalocket.euclid.RenderTask.run(RenderTask.java:35)
	at com.bermudalocket.euclid.Euclid$$Lambda$2078/281164406.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.bermudalocket.euclid.Euclid.renderTick(Euclid.java:84)
	at net.minecraft.class_757.handler$onRenderWorldLast$zcn000(class_757.java:1388)
	at net.minecraft.class_757.method_3178(class_757.java:1333)
	at net.minecraft.class_757.method_3188(class_757.java:1032)
	at net.minecraft.class_757.method_3192(class_757.java:792)
	at net.minecraft.class_310.method_1523(class_310.java:954)
	at net.minecraft.class_310.method_1514(class_310.java:410)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.bermudalocket.euclid.wecui.GhostWireframeHelper.expand(GhostWireframeHelper.java:16)
	at net.minecraft.class_408.lambda$onRender$3(class_408.java:567)
	at net.minecraft.class_408$$Lambda$2356/1362089915.run(Unknown Source)
	at com.bermudalocket.euclid.RenderTask.run(RenderTask.java:35)
	at com.bermudalocket.euclid.Euclid$$Lambda$2078/281164406.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.bermudalocket.euclid.Euclid.renderTick(Euclid.java:84)
	at net.minecraft.class_757.handler$onRenderWorldLast$zcn000(class_757.java:1388)
	at net.minecraft.class_757.method_3178(class_757.java:1333)
	at net.minecraft.class_757.method_3188(class_757.java:1032)

-- Affected level --
Details:
	All players: 2 total; [class_746['cheezychicken'/54727, l='MpServer', x=-1267.70, y=121.62, z=-92.30], class_745['CaptainDinghole'/1283, l='MpServer', x=-1265.70, y=115.00, z=-91.70]]
	Chunk stats: Client Chunk Cache: 169, 83
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-7,70,18), Chunk: (at 9,4,2 in -1,1; contains blocks -16,0,16 to -1,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 52670 game time, 39085628 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.14-SNAPSHOT:5c6bc18:1418) <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:574)
	at net.minecraft.class_310.method_1587(class_310.java:1923)
	at net.minecraft.class_310.method_1514(class_310.java:430)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 958066144 bytes (913 MB) / 1946157056 bytes (1856 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		euclid: Euclid 1.0.0-BETA
		fabric: Fabric API 0.3.0+build.206
		fabric-api-base: fabric-api-base 0.1.0+5914746342
		fabric-biomes-v1: fabric-biomes-v1 0.1.0+896c7fbb42
		fabric-commands-v0: fabric-commands-v0 0.1.1+25fd0c5242
		fabric-containers-v0: fabric-containers-v0 0.1.2+25fd0c5242
		fabric-content-registries-v0: fabric-content-registries-v0 0.1.1+05f11b7542
		fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.0+5914746342
		fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.0+ea100f6142
		fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.0+5914746342
		fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+1e69a0a542
		fabric-keybindings-v0: fabric-keybindings-v0 0.1.1+7dfef87c42
		fabric-loot-tables-v1: fabric-loot-tables-v1 0.1.0+43028fa642
		fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+ab421b9c42
		fabric-models-v0: fabric-models-v0 0.1.0+5914746342
		fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.1+25fd0c5242
		fabric-networking-v0: fabric-networking-v0 0.1.2+ea100f6142
		fabric-object-builders-v0: fabric-object-builders-v0 0.1.1+592d1d2242
		fabric-registry-sync-v0: fabric-registry-sync-v0 0.2.2+ea100f6142
		fabric-renderer-api-v1: fabric-renderer-api-v1 0.1.1+9486cfbf42
		fabric-renderer-indigo: fabric-renderer-indigo 0.1.9+9486cfbf42
		fabric-rendering-data-attachment-v1: fabric-rendering-data-attachment-v1 0.1.0+02a46d5b42
		fabric-rendering-fluids-v1: fabric-rendering-fluids-v1 0.1.0+dc4c57c242
		fabric-rendering-v0: fabric-rendering-v0 0.1.1+6dad974e42
		fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.1+7495ea2842
		fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.1+c189dc5c42
		fabric-textures-v0: fabric-textures-v0 0.1.4+792c1c3542
		fabricloader: Fabric Loader 0.4.8+build.158
		mm: Manningham Mills 1.6
		net_fabricmc_stitch: stitch 0.2.1.61
		optifabric: Optifabric 0.4.3
		org_slf4j_slf4j-api: slf4j-api 1.7.26
		org_slf4j_slf4j-simple: slf4j-simple 1.7.26
		org_zeroturnaround_zt-zip: zt-zip 1.13
		voxelmap: VoxelMap 1.9.13
	Launched Version: fabric-loader-0.4.8+build.158-1.14.4
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 431.36, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/1.14.4-r1.zip
	Current Language: English (United Kingdom)
	CPU: 12x AMD Ryzen 5 2600 Six-Core Processor

**Comment by bermudalocket** [comment]
This has been fixed in beta 2
