### ISSUE TITLE
client crashes on //expand 200 200 u

### ISSUE THREAD

**Issue by Silversunset01** [bermudalocket/Euclid#3]
**Describe the bug**
Typing `//expand 200 200 u` crashes the client

**To Reproduce**
1. make a WE selectin
2. type `//expand 200 200 u`
3. ???
4. Crash

**Expected behavior**
`//expand 200 200 u` should work the same as `//outset 200 -v` - it should expand the selection 200 blocks both up and down at the same time

**Screenshots and/or Logs**
```
[18:59:34] [main/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: null
	at com.bermudalocket.euclid.wecui.GhostWireframeHelper.expand(GhostWireframeHelper.java:16) ~[euclid-1.0.0-BETA.jar:?]
	at net.minecraft.class_408.lambda$onRender$3(class_408.java:567) ~[intermediary-fabric-loader-0.4.8+build.158-1.14.4.jar:?]
	at net.minecraft.class_408$$Lambda$2239/1757391382.run(Unknown Source) ~[?:?]
	at com.bermudalocket.euclid.RenderTask.run(RenderTask.java:35) ~[euclid-1.0.0-BETA.jar:?]
	at com.bermudalocket.euclid.Euclid$$Lambda$2101/270478498.accept(Unknown Source) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_51]
	at com.bermudalocket.euclid.Euclid.renderTick(Euclid.java:84) ~[euclid-1.0.0-BETA.jar:?]
	at net.minecraft.class_757.handler$onRenderWorldLast$zcn000(class_757.java:1388) ~[intermediary-fabric-loader-0.4.8+build.158-1.14.4.jar:?]
	at net.minecraft.class_757.method_3178(class_757.java:1333) ~[intermediary-fabric-loader-0.4.8+build.158-1.14.4.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1032) ~[intermediary-fabric-loader-0.4.8+build.158-1.14.4.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:792) ~[intermediary-fabric-loader-0.4.8+build.158-1.14.4.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:954) ~[intermediary-fabric-loader-0.4.8+build.158-1.14.4.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:410) [intermediary-fabric-loader-0.4.8+build.158-1.14.4.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:155) [intermediary-fabric-loader-0.4.8+build.158-1.14.4.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170) [fabric-loader-0.4.8+build.158.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129) [fabric-loader-0.4.8+build.158.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.4.8+build.158.jar:?]
```

**Environment**
 - OS: Windows 10
- Fabric version: v0.4.8+build.158
- multiplayer, haven planning, you know how.

**Additional context**
fixitfixitfixitfixitfixitfixit

**Comment by bermudalocket** [comment]
This NPE was caused by the mod parsing `//expand 200 200 u` with a matcher that was trained on `//expand # [a-zA-Z]{1}`. This is handled much more gracefully in beta 2, with the wireframe simply failing to render instead of crashing. Regarding support for all commands, see #4.
